### ISSUE TITLE
where is R2 loss?

### ISSUE THREAD

**Issue by zhangfeiyu5610** [yueyu1030/COSINE#17]
https://github.com/yueyu1030/COSINE/blob/a48e194ba6352b757f456cfc75127d7b6f0e17d8/trainer.py#L199

I want  to ask where does the R2 part of the original text appear in the code.

**Comment by yueyu1030** [comment]
Hi, R2 loss is in `calc_loss` function (https://github.com/yueyu1030/COSINE/blob/main/trainer.py#L75).
