### ISSUE TITLE
Among all the logs printed, which is the final result?

### ISSUE THREAD

**Issue by SageAgastya** [yueyu1030/COSINE#21]
Hey @yueyu1030 & @andreaspung , while running the code, there are many values of macro-f1 & accuracies, printed as logs over time. 
Please see the logs from ./eval/pred_agnews_test_1.txt:

- `Sun Oct 31 12:05:18 2021 w:1.0 decay=1.0e-04 Global Step:100 Macro_F1:0.6321, Micro_F1:0.7073
- Sun Oct 31 12:10:43 2021 w:1.0 decay=1.0e-04 Global Step:100 Macro_F1:0.6984, Micro_F1:0.7394
- Sun Oct 31 12:15:17 2021 w:1.0 decay=1.0e-04 Global Step:200 Macro_F1:0.7028, Micro_F1:0.7361
- Sun Oct 31 12:20:04 2021 w:1.0 decay=1.0e-04 Global Step:300 Macro_F1:0.7045, Micro_F1:0.7378
- Sun Oct 31 12:24:39 2021 w:1.0 decay=1.0e-04 Global Step:400 Macro_F1:0.7155, Micro_F1:0.7482
- Sun Oct 31 12:29:27 2021 w:1.0 decay=1.0e-04 Global Step:500 Macro_F1:0.7072, Micro_F1:0.7422
- Sun Oct 31 12:34:03 2021 w:1.0 decay=1.0e-04 Global Step:600 Macro_F1:0.7089, Micro_F1:0.7422
- Sun Oct 31 12:38:50 2021 w:1.0 decay=1.0e-04 Global Step:700 Macro_F1:0.7155, Micro_F1:0.7476
- Sun Oct 31 12:43:26 2021 w:1.0 decay=1.0e-04 Global Step:800 Macro_F1:0.7164, Micro_F1:0.7503
- Sun Oct 31 12:48:14 2021 w:1.0 decay=1.0e-04 Global Step:900 Macro_F1:0.7186, Micro_F1:0.7527
- Sun Oct 31 12:52:49 2021 w:1.0 decay=1.0e-04 Global Step:1000 Macro_F1:0.7172, Micro_F1:0.7474
- Sun Oct 31 12:57:36 2021 w:1.0 decay=1.0e-04 Global Step:1100 Macro_F1:0.7220, Micro_F1:0.7520
- Sun Oct 31 13:02:11 2021 w:1.0 decay=1.0e-04 Global Step:1200 Macro_F1:0.7204, Micro_F1:0.7515
- Sun Oct 31 13:07:28 2021 w:1.0 decay=1.0e-04 Global Step:1300 Macro_F1:0.7323, Micro_F1:0.7563
- Sun Oct 31 13:12:02 2021 w:1.0 decay=1.0e-04 Global Step:1400 Macro_F1:0.7246, Micro_F1:0.7502
- Sun Oct 31 13:16:47 2021 w:1.0 decay=1.0e-04 Global Step:1500 Macro_F1:0.7345, Micro_F1:0.7577
- Sun Oct 31 13:21:20 2021 w:1.0 decay=1.0e-04 Global Step:1600 Macro_F1:0.7346, Micro_F1:0.7563
- Sun Oct 31 13:26:03 2021 w:1.0 decay=1.0e-04 Global Step:1700 Macro_F1:0.7384, Micro_F1:0.7608
- Sun Oct 31 13:30:37 2021 w:1.0 decay=1.0e-04 Global Step:1800 Macro_F1:0.7439, Micro_F1:0.7632
- Sun Oct 31 13:35:22 2021 w:1.0 decay=1.0e-04 Global Step:1900 Macro_F1:0.7460, Micro_F1:0.7646
- Sun Oct 31 13:39:56 2021 w:1.0 decay=1.0e-04 Global Step:2000 Macro_F1:0.7445, Micro_F1:0.7641
- Sun Oct 31 13:44:41 2021 w:1.0 decay=1.0e-04 Global Step:2100 Macro_F1:0.7461, Micro_F1:0.7650
- Sun Oct 31 13:49:16 2021 w:1.0 decay=1.0e-04 Global Step:2200 Macro_F1:0.7440, Micro_F1:0.7644
- Sun Oct 31 13:54:00 2021 w:1.0 decay=1.0e-04 Global Step:2300 Macro_F1:0.7417, Micro_F1:0.7622
- Sun Oct 31 13:58:36 2021 w:1.0 decay=1.0e-04 Global Step:2400 Macro_F1:0.7441, Micro_F1:0.7623
- Sun Oct 31 14:03:20 2021 w:1.0 decay=1.0e-04 Global Step:2500 Macro_F1:0.7409, Micro_F1:0.7617
- Sun Oct 31 14:07:55 2021 w:1.0 decay=1.0e-04 Global Step:2600 Macro_F1:0.7422, Micro_F1:0.7621
- Sun Oct 31 14:12:38 2021 w:1.0 decay=1.0e-04 Global Step:2700 Macro_F1:0.7447, Micro_F1:0.7634
- Sun Oct 31 14:17:12 2021 w:1.0 decay=1.0e-04 Global Step:2800 Macro_F1:0.7457, Micro_F1:0.7648
- Sun Oct 31 14:21:53 2021 w:1.0 decay=1.0e-04 Global Step:2900 Macro_F1:0.7468, Micro_F1:0.7654
- Sun Oct 31 14:26:26 2021 w:1.0 decay=1.0e-04 Global Step:3000 Macro_F1:0.7461, Micro_F1:0.7651
- Sun Oct 31 14:28:08 2021 w:1.0 decay=1.0e-04 Global Step:-1 Macro_F1:0.7461, Micro_F1:0.7651

`

Among these logs, which one is the final result? Is it the last one which contains Global Step:-1?

Thanks in advance.

**Comment by yueyu1030** [comment]
Here you can refer to the model with the best performance on the development set. If the development set is not available in some cases, you can use the  last one which contains Global Step:-1 as the final performance.

**Comment by SageAgastya** [comment]
Thanks a lot.
