### ISSUE TITLE
Does improvement in weak-source always mean improvement in performance of learner?

### ISSUE THREAD

**Issue by SageAgastya** [yueyu1030/COSINE#22]
Hey @yueyu1030 @wren44 @andreaspung I have a weird observation with results of COSINE. 
I observed that improvement in the performance metric of weak source doesn't necessarily improve (but sometimes degrade) the performance of COSINE. 
For example:
```
Case-1:
weak source performance: 76.8%
COSINE: 85.3%
```
```
Case-2:
weak source performance: 79.3%
COSINE: 82.3%
```

Comparing case-1 & case-2, the same observation is explained through an example.

This observation has been validated by me over multiple weak-sources. Have you ever experienced this kind of behaviour in weak-supervised learning?

I request you to correct me if I am wrong asap so that I can go ahead with my work.

TIA!

**Comment by yueyu1030** [comment]
Hi,

In this case, I assume you have tuned the hyperparameter carefully (the optimal hyperparameter for case 1 and 2 might be different). 

Overall I believe better weak labels can lead to better end model performance, but there are some other issues such as the label distribution (if the weak labels are imbalanced, then the end model's performance might be even worse with more imbalanced label despite the accuracy for weak labels are higher). You could check it out and see whether it is the reason. 

Thanks!
