### ISSUE TITLE
the train() method when the input arg is ['clean', 'noisy', "noise"]

### ISSUE THREAD

**Issue by bhomass** [yueyu1030/COSINE#28]
Hi, when do these ['clean', 'noisy', "noise"] methods come in? They would trigger the method train() instead of selftrain()

I don't see them explained in the paper or the code.

**Comment by yueyu1030** [comment]
Hi, these methods are *not* used in our main experiments. For 'clean', it is used to study the labeling efficiency of the WS. For `noisy`, it is only used to analyze the performance of BERT fine-tuning on the noisy labeled dataset.
