### ISSUE TITLE
more questions on train()

### ISSUE THREAD

**Issue by bhomass** [yueyu1030/COSINE#30]
I asked about the use of train() method. the issue got closed. But the answer had an ambiguity. 

according to you, this method is not used except for clean and noisy, but the code says

        if args.method in ['clean', 'noisy', "noise"]:
            trainer.train()
            trainer.save_features()
        elif args.method == 'selftrain':
            trainer.train()
            trainer.selftrain(soft = args.soft_label)#, adv = args.add_adv)

This means train() is also called for selftrain

**Comment by yueyu1030** [comment]
For `selftrain` method (COSINE), we need to first fine-tune the pretrained LM on the weakly labeled dataset. This is why the train() function is used. Please refer to the section 3.1 of our paper [link](https://arxiv.org/pdf/2010.07835.pdf) for details.
