### ISSUE TITLE
What is the role of 'major'?

### ISSUE THREAD

**Issue by ibarrien** [yueyu1030/COSINE#5]
How are the 'major' values in the agnews data set used?
https://github.com/yueyu1030/COSINE/blob/2b735e4dbbb1a7231e407ebb0566d921da4f04e1/data_loader_new.py#L302

For supervised contrastive loss, are 'label' values sufficient so that 'major' values are not needed?

**Comment by yueyu1030** [comment]
Hi,

In our experiments, we use 'major' by default. 'major' means the weak label obtained via majority voting. 

For supervised contrastive loss, your understanding is correct.

Best,
Yue
