### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './eval/pred/pred_imdb_dev_selftrain_100.txt'

### ISSUE THREAD

**Issue by SageAgastya** [yueyu1030/COSINE#6]

**Comment by SageAgastya** [comment]
Dear Authors, firstly, there is a requirement missing in the repository so it would be helpful if "official_F1.py" is added to the repository. I have arranged script for official_f1 from  other source and have solved that problem for me.

Secondly, I was able to train the model for sometime on IMDB data but eventually ended up with this error. Pls let me know how to solve this error:

```
7/29/2021 12:40:24 - INFO - trainer -   ***** Running evaluation on dev dataset *****                                                                                   | 99/1095 [45:39<8:04:35, 29.19s/it]
07/29/2021 12:40:24 - INFO - trainer -     Num examples = 2500
07/29/2021 12:40:24 - INFO - trainer -     Batch size = 16
Evaluating: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [21:23<00:00,  8.17s/it]
iteration:0, w=1.0, Loss:0.584:   9%|███████████▌                                                                                                                    | 99/1095 [1:07:02<11:14:30, 40.63s/it]
Epoch:   0%|                                                                                                                                                                        | 0/3 [1:07:02<?, ?it/s]
Traceback (most recent call last):
  File "/Users/in-rktripathi/Documents/COSINE-main/main.py", line 113, in <module>
    main(args)
  File "/Users/in-rktripathi/Documents/COSINE-main/main.py", line 40, in main
    trainer.train()
  File "/Users/in-rktripathi/Documents/COSINE-main/trainer.py", line 308, in train
    self.evaluate('dev', global_step)
  File "/Users/in-rktripathi/Documents/COSINE-main/trainer.py", line 380, in evaluate
    write_prediction_tc(self.args, os.path.join(self.args.eval_dir, "pred/pred_%s_%s_%s_%d.txt"%(self.args.task, mode, self.args.method, global_step)), preds, self.id2label)
  File "/Users/in-rktripathi/Documents/COSINE-main/utils.py", line 68, in write_prediction_tc
    with open(output_file, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './eval/pred/pred_imdb_dev_selftrain_100.txt'
in-rktripathi@in-rktripathi COSINE-main % 

```

**Comment by yueyu1030** [comment]
Hi,

Please check whether the path './eval/pred' exists in your file system. If not, you can create an empty directory './eval/pred' so that the result file will be saved automatically. Thanks!

Best,
Yue

**Comment by SageAgastya** [comment]
Dear Yue,

Thank you for the suggestion, it helped me.
I have another query:
In you repository, there is a file "main.py" where you are using this
statements:
if args.pretrain:
trainer.pretrain()
I would like to add that this snippet is causing *AttributeError* saying
that "*args doesn't have pretrain as attribute"*.  Secondly, I can also see
that the *"Trainer"* class doesn't have a function definition for
*"pretrain()"* function.

I have commented out this snippet of code, to avoid error but originally it
was there in your script. Can you help me so that I can use these lines
without error.

Thank you,
Regards,
Rishabh

**Comment by yueyu1030** [comment]
The pretrain part is not used in our experiments. Thanks for pointing this out!
