### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'add_adv'

### ISSUE THREAD

**Issue by SageAgastya** [yueyu1030/COSINE#7]
Is there anyway out from this error:

`Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(args)
  File "main.py", line 41, in main
    trainer.selftrain(soft = args.soft_label, adv = args.add_adv)
AttributeError: 'Namespace' object has no attribute 'add_adv'
(/home/ec2-user/SageMaker/weak_supervision/env_p) sh-4.2$`

It seems add_adv is an attribute not handled well.

**Comment by yueyu1030** [comment]
Hi, 

Thanks for pointing this out! In our experiments, we set it to 'False' by default.
